### ISSUE TITLE
GUI: unlabeled checkbox leads to unexpected behavior

### ISSUE THREAD

**Issue by messersc** [bihealth/flowcelltool#26]
When adding libraries, there is an unlabeled checkbox at the end of each row.

![flowcells](https://cloud.githubusercontent.com/assets/9218116/24203402/de9f7e3c-0f15-11e7-8025-6725af04ec90.png)

If you want to add a library add check to box, nothing will happen after saving. To add a library, one has to leave all checkboxes empty.

Similarly, checking already existing libraries will remove them, which is possibly also unwanted.

**Comment by mikkonie** [comment]
This checkbox is created automatically by modelformset_factory when `can_delete=True`. By default no label is provided. [According to this](https://stackoverflow.com/a/28227216) an override can be used to specify the label. Alas, that approach does not work, at least with the package versions currently used in the project: the label gets changed but is still not rendered. As a workaround, I set the label using JQuery.
