### ISSUE TITLE
Secondary index sequence not shown in flowcell view

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/flowcelltool#62]
Probably a simple bug in the template.

**Comment by mikkonie** [comment]
This seems to be caused by `index_read_count` in FlowCell objects not getting correctly updated. Will investigate.

**Comment by mikkonie** [comment]
Scratch my previous comment, I misunderstood the issue. This was indeed due to a missing bit in the templates. Will be fixed in the next commit.
